! PDAF_V2.0

! $Id: generate_covar.F90 1604 2016-05-30 06:42:16Z lnerger $

!Modified by QT       2017-12-12 ---- for AWI-CM 
!Modified by QT       2017-12-19
!Modified by Frauke B 2022-02-22 ---- for FESOM2.1
!Modified by Frauke B 2022-11-03 ---- for FESOM2.1 JRA-forcing

! !Program: generate_covar --- Compute covariance matrix from state trajectory
PROGRAM generate_covar

! !DESCRIPTION:
! This programm to computes a covariance matrix from a state trajectory of
! the JRA atmospheric forcing for FESOM2.1. The matrix is decomposed in
! EOFs and stored in form of eigenvalues and eigenvectors.
!
! The matrix is generated by a singular value decomposition
! of the perturbation matrix of a long state trajectory
! about its long time mean.
!
! In this version:
! 1) the state vector is structured:
!    (huss, prra, prsn, psl, rlds, rsds, tas, uas, vas)^T;
! 2) JRA frequency is daily means;
! 3) only one output file, including the running mean, singular values and singular vectors
!
! !NOTES:
! Type "ulimit -s unlimited" before executing in case of segmentation
! fault error on Ollie.

! Three arrays (svdU, states, run_meanstate) each need:
! dimstate = 9x 126858; maxtimes = 73; REAL = 4 bytes
! allocate approx. 3x 300 MB

! !USES:
  IMPLICIT NONE

  INCLUDE 'netcdf.inc'


! Local variables
  
  CHARACTER(len=120) :: inpath, outpath                 ! File paths
  CHARACTER(len=120) :: infile_huss                     ! Humidity at sea surface
  CHARACTER(len=120) :: infile_prra                     ! Precipitation rain
  CHARACTER(len=120) :: infile_prsn                     ! Precipitation snow
  CHARACTER(len=120) :: infile_psl                      ! Pressure at sea level
  CHARACTER(len=120) :: infile_rlds                     ! Downward longwave radiation
  CHARACTER(len=120) :: infile_rsds                     ! Downward shortwave radiation
  CHARACTER(len=120) :: infile_tas                      ! Temperature
  CHARACTER(len=120) :: infile_uas                      ! Zonal winds
  CHARACTER(len=120) :: infile_vas                      ! Meridional winds
  CHARACTER(len=120) :: outfile                         ! File names   -- output
  CHARACTER(len=150) :: ncfile_in_huss, ncfile_in_prra, ncfile_in_prsn  ! File names including path
  CHARACTER(len=150) :: ncfile_in_psl , ncfile_in_rlds, ncfile_in_rsds  ! File names including path
  CHARACTER(len=150) :: ncfile_in_tas , ncfile_in_uas , ncfile_in_vas   ! File names including path
  CHARACTER(len=150) :: ncfile_out                      ! File name including path
  CHARACTER(len=150) :: attstr                          ! Attribute string for NC (NetCDF) output
  CHARACTER(len=4)   :: year
  
  INTEGER :: i, j, k, s, iter, maxtimes, rank           ! Counters
  INTEGER :: ncid_in_huss, ncid_in_prra, ncid_in_prsn   ! NC file IDs
  INTEGER :: ncid_in_psl , ncid_in_rlds, ncid_in_rsds   ! NC file IDs
  INTEGER :: ncid_in_tas , ncid_in_uas , ncid_in_vas    ! NC file IDs
  INTEGER :: ncid_out                                   ! NC file IDs
  INTEGER :: id_dim, id_time, id_state                  ! NC dimension and variable IDs
  INTEGER :: id_huss, id_prra, id_prsn                  ! Field variable IDs
  INTEGER :: id_psl , id_rlds, id_rsds                  ! Field variable IDs
  INTEGER :: id_tas , id_uas , id_vas                   ! Field variable IDs
  INTEGER :: id_mhuss, id_mprra, id_mprsn               ! Mean field variables IDs
  INTEGER :: id_mrlds, id_mrsds, id_mpsl                ! Mean field variables IDs
  INTEGER :: id_mtas, id_muas, id_mvas                  ! Mean field variables IDs
  INTEGER :: id_svdhuss, id_svdprra, id_svdprsn         ! Singular vector IDs
  INTEGER :: id_svdrlds, id_svdrsds, id_svdpsl          ! Singular vector IDs
  INTEGER :: id_svdtas,  id_svduas,  id_svdvas          ! Singular vector IDs
  INTEGER :: id_sigma, id_svec                          ! NC dimension and variable IDs
  INTEGER :: dimid_rank, dimid_state, dimid_nfields     ! NC dimension and variable IDs
  INTEGER :: dimid_nod2                                 ! NC dimension and variable IDs
!~   INTEGER :: dimid_2D, dimid_tracer3D, dimid_w          ! NC dimension and variable IDs
  INTEGER :: dimid_maxtimes                             ! NC dimension and variable IDs
  INTEGER :: nod2                                       ! Number of 2D nodes
  INTEGER :: steps, dim_state                           ! Dimensions
  INTEGER :: stat(100)                                  ! Status for NC operations
  INTEGER :: countv2(2), startv2(2)                     ! Vectors for NC operations (2D)
  INTEGER :: countv1, startv1                           ! Vectors for NC operations (1D)
  INTEGER :: dimids(2)                                  ! Vector for NC operations 
  INTEGER :: dim_fields(9)                              ! Size of field
  INTEGER :: nfields                                    ! Number of fields
  INTEGER :: offsets(9)                                 ! Offset of fields
  INTEGER :: id_field                                   ! Field
  INTEGER :: hwindow                                    ! Half time window
  INTEGER :: ostep                                      ! Time step                             
  REAL    :: stddev(9)                                  ! STDDEV of field
  INTEGER :: status                                     ! Status Flag for PDAF routine
  
  REAL :: limit                                         ! Lower limit for singular values
  
  REAL,    ALLOCATABLE :: times(:)                         ! Array of times from NC file
  REAL(4), ALLOCATABLE :: states(:,:)                      ! State trajectory
  REAL,    ALLOCATABLE :: states8(:,:)                     ! State as double (required for PDAF)
  REAL,    ALLOCATABLE :: run_meanstate (:,:)              ! Running mean state
  REAL,    ALLOCATABLE :: meanstate(:)                     ! Mean state of trajectory
  REAL,    ALLOCATABLE,DIMENSION(:) :: svals                ! field of singular values
  REAL,    ALLOCATABLE,DIMENSION(:,:) :: svdU               ! left singular vectors

  ! Controls for PDAF_eofcovar
  INTEGER :: remove_mean  ! (1) Let PDAF_eofcovar compute and subtract the mean state;
                          ! (0) mean already removed from trajectory
  INTEGER :: do_mv        ! (1) to perform multivariate normalization; (0) no normalization


! ************************************************
! *** Configuration                            ***
! ************************************************

  ! Maximum number of time slices to consider
  maxtimes = 72
  
  ! Number of nodes on CORE2 grid:
  nod2              = 126858

  ! Set do_mv=1 to activate normalization; 0 to run without normalization
  do_mv = 1   

  ! Path to and name of file holding model trajectory
  year = '2016'
  inpath = '/work/ollie/frbunsen/jra_core2/'
  infile_huss = 'huss.daily.'//year//'.nc'
  infile_prra = 'prra.daily.'//year//'.nc'
  infile_prsn = 'prsn.daily.'//year//'.nc'
  infile_psl  = 'psl.daily.' //year//'.nc'
  infile_rlds = 'rlds.daily.'//year//'.nc'
  infile_rsds = 'rsds.daily.'//year//'.nc'
  infile_tas  = 'tas.daily.' //year//'.nc'
  infile_uas  = 'uas.daily.' //year//'.nc'
  infile_vas  = 'vas.daily.' //year//'.nc'
  
  ! Path to and name of output file holding covariance matrix
  outpath = '/work/ollie/frbunsen/jra_core2/cov/'
  outfile = 'cov.nc'

  ! Lower limit for eigenvalue
  limit = 1.0e-12

  ! Number of fields in state vector
  nfields = 9

  ! Half time window for running mean (2*irange+1)
  hwindow = 6 ! 6
  
  ! Time step (only consider every x-th value)
  ostep = 1  ! every day in daily input data

  ! Note: multivariate normalization can be useful if there are several fields
  !       with difference variances. Here, we have 9 fields.

! ************************************************
! *** Init                                     ***
! ************************************************

  WRITE (*,'(10x,a)')  '*******************************************'
  WRITE (*,'(10x,a)')  '*             GENERATE_COVAR              *'
  WRITE (*,'(10x,a)')  '*                                         *'
  WRITE (*,'(10x,a)')  '*    Compute covariance matrix and mean   *'
  WRITE (*,'(10x,a)')  '*     state from a sequence of states.    *'
  WRITE (*,'(10x,a)')  '*                                         *'
  WRITE (*,'(10x,a)')  '*   Write covar matrix as scaled eigen-   *'
  WRITE (*,'(10x,a)')  '*    vectors and singular values into     *'
  WRITE (*,'(10x,a)')  '*              NetCDF file                *'
  WRITE (*,'(10x,a/)') '*******************************************'

  ncfile_in_huss = TRIM(inpath)//TRIM(infile_huss)
  WRITE (*,*) 'Read HUSS from file:  ',TRIM(ncfile_in_huss)
  ncfile_in_prra = TRIM(inpath)//TRIM(infile_prra)
  WRITE (*,*) 'Read PRRA from file:  ',TRIM(ncfile_in_prra)
  ncfile_in_prsn = TRIM(inpath)//TRIM(infile_prsn)
  WRITE (*,*) 'Read PRSN from file:  ',TRIM(ncfile_in_prsn)
  ncfile_in_psl = TRIM(inpath)//TRIM(infile_psl)
  WRITE (*,*) 'Read PSL from file:   ',TRIM(ncfile_in_psl)
  ncfile_in_rlds = TRIM(inpath)//TRIM(infile_rlds)
  WRITE (*,*) 'Read RLDS from file:  ',TRIM(ncfile_in_rlds)
  ncfile_in_rsds = TRIM(inpath)//TRIM(infile_rsds)
  WRITE (*,*) 'Read RSDS from file:  ',TRIM(ncfile_in_rsds)
  ncfile_in_tas = TRIM(inpath)//TRIM(infile_tas)
  WRITE (*,*) 'Read TAS from file:   ',TRIM(ncfile_in_tas)
  ncfile_in_uas = TRIM(inpath)//TRIM(infile_uas)
  WRITE (*,*) 'Read UAS from file:   ',TRIM(ncfile_in_uas)
  ncfile_in_vas = TRIM(inpath)//TRIM(infile_vas)
  WRITE (*,*) 'Read VAS from file:   ',TRIM(ncfile_in_vas)

  ncfile_out = TRIM(outpath)//TRIM(outfile)
  WRITE (*,*) 'Write output to file: ',TRIM(ncfile_out)

! *****************************************************
! *** Open HUSS trajectory file and read dimensions ***
! *****************************************************

  s = 1
  stat(s) = NF_OPEN(TRIM(ncfile_in_huss), NF_NOWRITE, ncid_in_huss)
  s = s + 1

  ! Get state variable ID
  stat(s) = NF_INQ_VARID(ncid_in_huss, 'huss', id_huss)

  DO i = 1,  s
     IF (stat(i) /= NF_NOERR) &
          WRITE(*, *) 'NetCDF error in reading dimensions of huss file, no.', i
  END DO
  
! *****************************************************
! *** Open PRRA trajectory file and read dimensions ***
! *****************************************************

  s = 1
  stat(s) = NF_OPEN(TRIM(ncfile_in_prra), NF_NOWRITE, ncid_in_prra)
  s = s + 1

  ! Get state variable ID
  stat(s) = NF_INQ_VARID(ncid_in_prra, 'prra', id_prra)

  DO i = 1,  s
     IF (stat(i) /= NF_NOERR) &
          WRITE(*, *) 'NetCDF error in reading dimensions of prra file, no.', i
  END DO

! *****************************************************
! *** Open PRSN trajectory file and read dimensions ***
! *****************************************************

  s = 1
  stat(s) = NF_OPEN(TRIM(ncfile_in_prsn), NF_NOWRITE, ncid_in_prsn)
  s = s + 1

  ! Get state variable ID
  stat(s) = NF_INQ_VARID(ncid_in_prsn, 'prsn', id_prsn)

  DO i = 1,  s
     IF (stat(i) /= NF_NOERR) &
          WRITE(*, *) 'NetCDF error in reading dimensions of prsn file, no.', i
  END DO
  
! ****************************************************
! *** Open PSL trajectory file and read dimensions ***
! ****************************************************

  s = 1
  stat(s) = NF_OPEN(TRIM(ncfile_in_psl), NF_NOWRITE, ncid_in_psl)
  s = s + 1

  ! Get state variable ID
  stat(s) = NF_INQ_VARID(ncid_in_psl, 'psl', id_psl)

  DO i = 1,  s
     IF (stat(i) /= NF_NOERR) &
          WRITE(*, *) 'NetCDF error in reading dimensions of psl file, no.', i
  END DO

! *****************************************************
! *** Open RLDS trajectory file and read dimensions ***
! *****************************************************

  s = 1
  stat(s) = NF_OPEN(TRIM(ncfile_in_rlds), NF_NOWRITE, ncid_in_rlds)
  s = s + 1

  ! Get state variable ID
  stat(s) = NF_INQ_VARID(ncid_in_rlds, 'rlds', id_rlds)

  DO i = 1,  s
     IF (stat(i) /= NF_NOERR) &
          WRITE(*, *) 'NetCDF error in reading dimensions of rlds file, no.', i
  END DO
  
! *****************************************************
! *** Open RSDS trajectory file and read dimensions ***
! *****************************************************

  s = 1
  stat(s) = NF_OPEN(TRIM(ncfile_in_rsds), NF_NOWRITE, ncid_in_rsds)
  s = s + 1

  ! Get state variable ID
  stat(s) = NF_INQ_VARID(ncid_in_rsds, 'rsds', id_rsds)

  DO i = 1,  s
     IF (stat(i) /= NF_NOERR) &
          WRITE(*, *) 'NetCDF error in reading dimensions of rsds file, no.', i
  END DO
  
! ****************************************************
! *** Open TAS trajectory file and read dimensions ***
! ****************************************************

  s = 1
  stat(s) = NF_OPEN(TRIM(ncfile_in_tas), NF_NOWRITE, ncid_in_tas)
  s = s + 1

  ! Get state variable ID
  stat(s) = NF_INQ_VARID(ncid_in_tas, 'tas', id_tas)

  DO i = 1,  s
     IF (stat(i) /= NF_NOERR) &
          WRITE(*, *) 'NetCDF error in reading dimensions of tas file, no.', i
  END DO
  
! ****************************************************
! *** Open UAS trajectory file and read dimensions ***
! ****************************************************

  s = 1
  stat(s) = NF_OPEN(TRIM(ncfile_in_uas), NF_NOWRITE, ncid_in_uas)
  s = s + 1

  ! Get state variable ID
  stat(s) = NF_INQ_VARID(ncid_in_uas, 'uas', id_uas)

  DO i = 1,  s
     IF (stat(i) /= NF_NOERR) &
          WRITE(*, *) 'NetCDF error in reading dimensions of uas file, no.', i
  END DO
  
! ****************************************************
! *** Open VAS trajectory file and read dimensions ***
! ****************************************************

  s = 1
  stat(s) = NF_OPEN(TRIM(ncfile_in_vas), NF_NOWRITE, ncid_in_vas)
  s = s + 1

  ! Get state variable ID
  stat(s) = NF_INQ_VARID(ncid_in_vas, 'vas', id_vas)
  
  ! Get time ID
  s = s + 1
  stat(s) = NF_INQ_DIMID(ncid_in_vas, 'time', id_dim)
  s = s + 1
  stat(s) = NF_INQ_DIMLEN(ncid_in_vas, id_dim, steps)
  
  ! Initialize time array
  ALLOCATE(times(steps))
  s = s + 1
  stat(s) = NF_INQ_VARID(ncid_in_vas, 'time', id_time)
  s = s + 1
  stat(s) = NF_GET_VAR_DOUBLE(ncid_in_vas, id_time, times)

  DO i = 1,  s
     IF (stat(i) /= NF_NOERR) &
          WRITE(*, *) 'NetCDF error in reading dimensions of vas file, no.', i
  END DO

  ! Write dimensions
  WRITE (*,'(/1x,a)') 'Dimensions of in-data:'
  WRITE (*,'(10x,1x,a25,i12)') 'nod2       ', nod2
  WRITE (*,'(10x,1x,a25,i12)') 'nfields    ', nfields
  WRITE (*,'(10x,1x,a25,i12)') 'time steps ', steps

  IF (steps < ((maxtimes-1)*ostep+1)) THEN
     WRITE (*,'(1x,a)') '!! Number of available time slices is smaller than maxtimes - resetting!'
     maxtimes = steps/ostep
  END IF
  
  WRITE (*,'(10x,1x,a25,i12)') 'maxtimes   ', maxtimes

! ******************************************************************
! *** Define state vector                                        ***
! ******************************************************************
  
  ! Define field dimensions
  dim_fields (1) = nod2
  dim_fields (2) = nod2
  dim_fields (3) = nod2
  dim_fields (4) = nod2
  dim_fields (5) = nod2
  dim_fields (6) = nod2
  dim_fields (7) = nod2
  dim_fields (8) = nod2
  dim_fields (9) = nod2


 ! Define state dimension
  dim_state =  SUM(dim_fields)

  WRITE (*,'(10x,1x,a25,i12)') 'dim_state  ', dim_state


  ! Define offsets
  offsets (1) = 0                        
  offsets (2) = offsets(1) + nod2        
  offsets (3) = offsets(2) + nod2        
  offsets (4) = offsets(3) + nod2        
  offsets (5) = offsets(4) + nod2        
  offsets (6) = offsets(5) + nod2        
  offsets (7) = offsets(6) + nod2        
  offsets (8) = offsets(7) + nod2        
  offsets (9) = offsets(8) + nod2        


! ****************************
! *** Read trajectory data ***
! ****************************

  WRITE (*,'(/1x,a)') '------- Read trajectory -------------'
  ALLOCATE(states(dim_state, maxtimes))
  
  read_in: DO iter = ostep, maxtimes*ostep, ostep
 
  ! Read HUSS (dim: ncells,time)
  IF (iter==ostep) THEN
  WRITE (*,'(/1x,a)') '- Read HUSS at step 1'
  END IF
  
  startv2(1) = 1     
  countv2(1) = nod2  ! get nod2 (i.e. all) elements starting from 1
  startv2(2) = iter/ostep
  countv2(2) = 1     ! get one element at time step "iter"
  
  stat(1) = NF_GET_VARA_REAL(ncid_in_huss, id_huss, startv2, countv2, &
      states(offsets(1)+1: offsets(1)+dim_fields(1), iter/ostep))

  IF (stat(1) /= NF_NOERR) &
      WRITE(*, *) 'NetCDF error in reading HUSS'
      
      
  ! Read PRRA (dim: time, ncells)
  IF (iter==ostep) THEN
  WRITE (*,'(/1x,a)') '- Read PRRA at step 1'
  END IF
  
  stat(1) = NF_GET_VARA_REAL(ncid_in_prra, id_prra, startv2, countv2, &
      states(offsets(2)+1: offsets(2)+dim_fields(2), iter/ostep))

  IF (stat(1) /= NF_NOERR) &
      WRITE(*, *) 'NetCDF error in reading PRRA'
      
      
  ! Read PRSN (dim: time, ncells)
  IF (iter==ostep) THEN
  WRITE (*,'(/1x,a)') '- Read PRSN at step 1'
  END IF
  
  stat(1) = NF_GET_VARA_REAL(ncid_in_prsn, id_prsn, startv2, countv2, &
      states(offsets(3)+1: offsets(3)+dim_fields(3), iter/ostep))

  IF (stat(1) /= NF_NOERR) &
      WRITE(*, *) 'NetCDF error in reading PRSN'
      
      
  ! Read PSL (dim: time, ncells)
  IF (iter==ostep) THEN
  WRITE (*,'(/1x,a)') '- Read PSL at step 1'
  END IF
  
  stat(1) = NF_GET_VARA_REAL(ncid_in_psl, id_psl, startv2, countv2, &
      states(offsets(4)+1: offsets(4)+dim_fields(4), iter/ostep))

  IF (stat(1) /= NF_NOERR) &
      WRITE(*, *) 'NetCDF error in reading PSL'
      
      
  ! Read RLDS (dim: time, ncells)
  IF (iter==ostep) THEN
  WRITE (*,'(/1x,a)') '- Read RLDS at step 1'
  END IF
  
  stat(1) = NF_GET_VARA_REAL(ncid_in_rlds, id_rlds, startv2, countv2, &
      states(offsets(5)+1: offsets(5)+dim_fields(5), iter/ostep))

  IF (stat(1) /= NF_NOERR) &
      WRITE(*, *) 'NetCDF error in reading RLDS'
  
  
  ! Read RSDS (dim: time, ncells)
  IF (iter==ostep) THEN
  WRITE (*,'(/1x,a)') '- Read RSDS at step 1'
  END IF
  
  stat(1) = NF_GET_VARA_REAL(ncid_in_rsds, id_rsds, startv2, countv2, &
      states(offsets(6)+1: offsets(6)+dim_fields(6), iter/ostep))

  IF (stat(1) /= NF_NOERR) &
      WRITE(*, *) 'NetCDF error in reading RSDS'


  ! Read TAS (dim: time, ncells)
  IF (iter==ostep) THEN
  WRITE (*,'(/1x,a)') '- Read TAS at step 1'
  END IF
  
  stat(1) = NF_GET_VARA_REAL(ncid_in_tas, id_tas, startv2, countv2, &
      states(offsets(7)+1: offsets(7)+dim_fields(7), iter/ostep))

  IF (stat(1) /= NF_NOERR) &
      WRITE(*, *) 'NetCDF error in reading TAS'


  ! Read UAS (dim: time, ncells)
  IF (iter==ostep) THEN
  WRITE (*,'(/1x,a)') '- Read UAS at step 1'
  END IF
  
  stat(1) = NF_GET_VARA_REAL(ncid_in_uas, id_uas, startv2, countv2, &
      states(offsets(8)+1: offsets(8)+dim_fields(8), iter/ostep))

  IF (stat(1) /= NF_NOERR) &
      WRITE(*, *) 'NetCDF error in reading UAS'


  ! Read VAS (dim: time, ncells)
  IF (iter==ostep) THEN
  WRITE (*,'(/1x,a)') '- Read VAS at step 1'
  END IF
  
  stat(1) = NF_GET_VARA_REAL(ncid_in_vas, id_vas, startv2, countv2, &
      states(offsets(9)+1: offsets(9)+dim_fields(9), iter/ostep))

  IF (stat(1) /= NF_NOERR) &
      WRITE(*, *) 'NetCDF error in reading UAS'

      
  END DO read_in

  ! Close trajectory file

  stat(1) = nf_close(ncid_in_huss)
  IF (stat(1) /= NF_NOERR) &
  WRITE(*, *) 'NetCDF error in closing HUSS trajectory file'

  stat(1) = nf_close(ncid_in_prra)
  IF (stat(1) /= NF_NOERR) &
  WRITE(*, *) 'NetCDF error in closing PRRA trajectory file'

  stat(1) = nf_close(ncid_in_prsn)
  IF (stat(1) /= NF_NOERR) &
  WRITE(*, *) 'NetCDF error in closing PRSN trajectory file'

  stat(1) = nf_close(ncid_in_psl)
  IF (stat(1) /= NF_NOERR) &
  WRITE(*, *) 'NetCDF error in closing PSL trajectory file'

  stat(1) = nf_close(ncid_in_rlds)
  IF (stat(1) /= NF_NOERR) &
  WRITE(*, *) 'NetCDF error in closing RLDS trajectory file'

  stat(1) = nf_close(ncid_in_rsds)
  IF (stat(1) /= NF_NOERR) &
  WRITE(*, *) 'NetCDF error in closing RSDS trajectory file'
       
  stat(1) = nf_close(ncid_in_tas)
  IF (stat(1) /= NF_NOERR) &
  WRITE(*, *) 'NetCDF error in closing TAS trajectory file'
  
  stat(1) = nf_close(ncid_in_uas)
  IF (stat(1) /= NF_NOERR) &
  WRITE(*, *) 'NetCDF error in closing UAS trajectory file'
  
  stat(1) = nf_close(ncid_in_vas)
  IF (stat(1) /= NF_NOERR) &
  WRITE(*, *) 'NetCDF error in closing VAS trajectory file'



! **********************************
! *** Compute running mean state ***
! **********************************

  WRITE (*,*) 'Compute running mean over', maxtimes,' snapshots at every ', ostep, '-th step of input data'
  ALLOCATE(meanstate(dim_state))
  ALLOCATE(run_meanstate(dim_state, maxtimes))
  
  DO i = 1, maxtimes
     meanstate = 0.0

     IF (i > hwindow .AND. i <= (maxtimes - hwindow)) THEN
        Do j = i - hwindow, i + hwindow
           meanstate = meanstate + states (:, j)
        END DO

     ELSE IF (i <= hwindow) THEN
        DO j = 1, i + hwindow
           meanstate = meanstate + states (:, j)
        END DO
        DO j = maxtimes - hwindow +i, maxtimes
           meanstate = meanstate + states (:, j)
        END DO

     ELSE IF (i > maxtimes - hwindow) THEN
        DO j = i - hwindow, maxtimes
           meanstate = meanstate + states (:, j)
        END DO        
        DO j = 1, i + hwindow - maxtimes
            meanstate = meanstate + states (:, j)
        END DO
     END IF
     
     meanstate = meanstate / (2 * hwindow + 1)
     run_meanstate (:, i) = meanstate
 
  END DO
  
  ! get residual
  states = states - run_meanstate

! *********************************************************
! *** Singular value decomposition of covariance matrix ***
! ***                                                   ***
! *** The covariance matrix is given by the state       ***
! *** sequences X of k states as                        ***
! ***          -1    _     _ T        T                 ***
! *** P = (k-1)   (X-X) (X-X)  = U L U  (EVP)           ***
! ***                                                   ***
! *** Thus we compute the singular value decomposition  ***
! ***     _        T            -1    2  T              ***
! ***   X-X = U S V ;  P = (k-1)   U S  U               ***
! ***                                                   ***
! ***                         -1/2                      ***
! *** and we store U and (k-1)     S in a NetCDF file.  ***
! *********************************************************

  WRITE (*,'(/1x,a)') '------- Compute covariance matrix decomposition -------------'

  ! PDAF_eofcovar should compute and subtract the mean state from Trajectory 
  ! before decomposition. Afterwards, it's added again.
  remove_mean = 0

  ! Allocate arrays for singular values and vectors
  WRITE(*, *) 'Allocate svals'
  ALLOCATE(svals(maxtimes))
  
  WRITE(*, *) 'Allocate svdU'
  ALLOCATE(svdU(dim_state, maxtimes))
  
  WRITE(*, *) 'Call routine generating matrix decomposition'
  
  
  
  ! Call routine generating matrix decomposition
  
!~   WRITE(*,*) 'Frauke debug dim_state: ', dim_state
!~   WRITE(*,*) 'Frauke debug maxtimes:  ', maxtimes
!~   WRITE(*,*) 'Frauke debug nfields:   ', nfields
!~   WRITE(*,*) 'Frauke debug dim_fields:', dim_fields
!~   WRITE(*,*) 'Frauke debug offsets:   ', offsets
!~   WRITE(*,*) 'Frauke debug do_mv:     ', do_mv
!~   WRITE(*,*) 'Frauke debug shape(states):', shape(states)
!~   WRITE(*,*) 'Frauke debug states(1:4)', states(1:2,1:2)
!~   WRITE(*,*) 'Frauke debug shape(meanstate):', shape(meanstate)
!~   WRITE(*,*) 'Frauke debug meanstate(1:4)', meanstate(1:2)

  ALLOCATE(states8(dim_state,maxtimes))
  states8 = REAL(states,8)
  
  CALL PDAF_eofcovar(dim_state, maxtimes, nfields, dim_fields, offsets, &
       remove_mean, do_mv, states8, stddev, svals, svdU, meanstate, 1, status)

 
! *********************************************************
! *** Write mean state and decomposed covariance matrix ***
! *********************************************************

  ! *** Determine rank to write ***

  getlimit: DO i = 1, maxtimes
     IF (svals(i) >= limit) THEN
        rank = i
     ELSE
        EXIT getlimit
     END IF
  END DO getlimit
  IF (rank < maxtimes) THEN
     WRITE (*,'(1x,a,i6,a,es10.2)') &
          'Use maximum of ', rank, ' eigenvectors due to eigenvalue-limit of ',limit
  END IF
  IF (rank == maxtimes) THEN
     rank = maxtimes - 1
     WRITE (*,'(5x,a,i4)') '++ reset rank to ',rank
  END IF

  WRITE (*,'(5x,a)') 'Singular values: '
  DO i = 1, rank
    WRITE (*, '(10x, i4, es12.3)') i, svals(i)
  END DO


  WRITE (*,'(/1x,a)') '------- Write decomposed covariance matrix -------------'

  ! *** Initialize file
  s = 1
  stat(s) = NF_CREATE(ncfile_out, NF_64BIT_OFFSET, ncid_out)

  IF (do_mv == 1) THEN
     attstr = 'Running mean state, scaled singular vectors and values of multivariate decomposed covariance matrix for FESOM2.1 JRA forcing'
  ELSE
     attstr = 'Running mean state, singular vectors and values of decomposed covariance matrix for FESOM2.1 JRA forcing'
  END IF

  s = s + 1
  stat(s) = NF_PUT_ATT_TEXT(ncid_out, NF_GLOBAL, 'title', LEN_TRIM(attstr), &
       TRIM(attstr))

  attstr = 'HUSS, PRRA, PRSN, PSL, RLDS, RSDS, TAS, UAS, VAS'
  s = s + 1
  stat(s) = NF_PUT_ATT_TEXT(ncid_out, NF_GLOBAL, 'state_fields', LEN_TRIM(attstr), &
       TRIM(attstr))
       

  ! Define dimensions
  s = s + 1
  stat(s) = NF_DEF_DIM(ncid_out, 'rank', rank, dimid_rank)
  s = s + 1
  stat(s) = NF_DEF_DIM(ncid_out, 'nod2', nod2, dimid_nod2)
  s = s + 1
  stat(s) = NF_DEF_DIM(ncid_out, 'dim_state', dim_state, dimid_state)
  s = s + 1
  stat(s) = NF_DEF_DIM(ncid_out, 'nfields',  nfields, dimid_nfields)

  ! Define variables
  ! singular values
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'sigma', NF_DOUBLE, 1, dimid_rank, Id_sigma)
 
  ! mean state
  
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'huss_mean', NF_REAL, 1, dimid_nod2, id_mhuss)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'prra_mean', NF_REAL, 1, dimid_nod2, id_mprra)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'prsn_mean', NF_REAL, 1, dimid_nod2, id_mprsn)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'psl_mean' , NF_REAL, 1, dimid_nod2, id_mpsl)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'rlds_mean', NF_REAL, 1, dimid_nod2, id_mrlds)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'rsds_mean', NF_REAL, 1, dimid_nod2, id_mrsds)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'tas_mean' , NF_REAL, 1, dimid_nod2, id_mtas)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'uas_mean' , NF_REAL, 1, dimid_nod2, id_muas)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'vas_mean' , NF_REAL, 1, dimid_nod2, id_mvas)

  ! singular vectors
  
  dimids(1) = dimid_nod2
  dimids(2) = dimid_rank
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'huss_svd', NF_REAL, 2, dimids, id_svdhuss)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'prra_svd', NF_REAL, 2, dimids, id_svdprra)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'prsn_svd', NF_REAL, 2, dimids, id_svdprsn)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'psl_svd' , NF_REAL, 2, dimids, id_svdpsl)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'rlds_svd', NF_REAL, 2, dimids, id_svdrlds)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'rsds_svd', NF_REAL, 2, dimids, id_svdrsds)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'tas_svd' , NF_REAL, 2, dimids, id_svdtas)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'uas_svd' , NF_REAL, 2, dimids, id_svduas)
  s = s + 1
  stat(s) = NF_DEF_VAR(ncid_out, 'vas_svd' , NF_REAL, 2, dimids, id_svdvas)

  ! End Define mode
  s = s + 1
  stat(s) = NF_ENDDEF(ncid_out)

  DO i = 1,  s
     IF (stat(i) /= NF_NOERR) &
          WRITE(*, *) 'NetCDF error in init of output file, no.', i
  END DO

  ! Write singular values
  s = 1
  stat(s) = NF_PUT_VAR_DOUBLE(ncid_out, id_sigma, svals(1:rank))
  
  ! Write running mean (for the last snap shot)
  
  startv1 = 1
  countv1 = nod2
  s = s + 1
  stat(s) = NF_PUT_VARA_REAL(ncid_out, id_mhuss, startv1, countv1, &
            REAL(run_meanstate(offsets(1)+1 : offsets(1)+dim_fields(1), maxtimes), 4))
  s = s + 1
  stat(s) = NF_PUT_VARA_REAL(ncid_out, id_mprra, startv1, countv1, &
            REAL(run_meanstate(offsets(2)+1 : offsets(2)+dim_fields(2), maxtimes), 4))
  s = s + 1
  stat(s) = NF_PUT_VARA_REAL(ncid_out, id_mprsn, startv1, countv1, &
            REAL(run_meanstate(offsets(3)+1 : offsets(3)+dim_fields(3), maxtimes), 4))
  s = s + 1
  stat(s) = NF_PUT_VARA_REAL(ncid_out, id_mpsl , startv1, countv1, &
            REAL(run_meanstate(offsets(4)+1 : offsets(4)+dim_fields(4), maxtimes), 4))
  s = s + 1
  stat(s) = NF_PUT_VARA_REAL(ncid_out, id_mrlds, startv1, countv1, &
            REAL(run_meanstate(offsets(5)+1 : offsets(5)+dim_fields(5), maxtimes), 4))
  s = s + 1
  stat(s) = NF_PUT_VARA_REAL(ncid_out, id_mrsds, startv1, countv1, &
            REAL(run_meanstate(offsets(6)+1 : offsets(6)+dim_fields(6), maxtimes), 4))
  s = s + 1
  stat(s) = NF_PUT_VARA_REAL(ncid_out, id_mtas , startv1, countv1, &
            REAL(run_meanstate(offsets(7)+1 : offsets(7)+dim_fields(7), maxtimes), 4))
  s = s + 1
  stat(s) = NF_PUT_VARA_REAL(ncid_out, id_muas , startv1, countv1, &
            REAL(run_meanstate(offsets(8)+1 : offsets(8)+dim_fields(8), maxtimes), 4))
  s = s + 1
  stat(s) = NF_PUT_VARA_REAL(ncid_out, id_mvas , startv1, countv1, &
            REAL(run_meanstate(offsets(9)+1 : offsets(9)+dim_fields(9), maxtimes), 4))

  DO i = 1,  s
     IF (stat(i) /= NF_NOERR) &
          WRITE(*, *) 'NetCDF error in writing running mean state, no.', i
  END DO


  ! *** Write singular vectors

  writevectors: DO i = 1, rank
  
     s=1

     startv2(2) = i
     countv2(2) = 1
     startv2(1) = 1
     countv2(1) = nod2
     s = s + 1
     stat(s) = NF_PUT_VARA_REAL(ncid_out, id_svdhuss, startv2, countv2, &
          REAL(svdU(offsets(1)+1 : offsets(1)+dim_fields(1), i), 4))
     s = s + 1
     stat(s) = NF_PUT_VARA_REAL(ncid_out, id_svdprra, startv2, countv2, &
          REAL(svdU(offsets(2)+1 : offsets(2)+dim_fields(2), i), 4))
     s = s + 1
     stat(s) = NF_PUT_VARA_REAL(ncid_out, id_svdprsn, startv2, countv2, &
          REAL(svdU(offsets(3)+1 : offsets(3)+dim_fields(3), i), 4))
     s = s + 1
     stat(s) = NF_PUT_VARA_REAL(ncid_out, id_svdpsl , startv2, countv2, &
          REAL(svdU(offsets(4)+1 : offsets(4)+dim_fields(4), i), 4))
     s = s + 1
     stat(s) = NF_PUT_VARA_REAL(ncid_out, id_svdrlds, startv2, countv2, &
          REAL(svdU(offsets(5)+1 : offsets(5)+dim_fields(5), i), 4))
     s = s + 1
     stat(s) = NF_PUT_VARA_REAL(ncid_out, id_svdrsds, startv2, countv2, &
          REAL(svdU(offsets(6)+1 : offsets(6)+dim_fields(6), i), 4))
     s = s + 1
     stat(s) = NF_PUT_VARA_REAL(ncid_out, id_svdtas, startv2, countv2, &
          REAL(svdU(offsets(7)+1 : offsets(7)+dim_fields(7), i), 4))
     s = s + 1
     stat(s) = NF_PUT_VARA_REAL(ncid_out, id_svduas, startv2, countv2, &
          REAL(svdU(offsets(8)+1 : offsets(8)+dim_fields(8), i), 4))
     s = s + 1
     stat(s) = NF_PUT_VARA_REAL(ncid_out, id_svdvas, startv2, countv2, &
          REAL(svdU(offsets(9)+1 : offsets(9)+dim_fields(9), i), 4))

     DO k = 1,  s
        IF (stat(k) /= NF_NOERR) &
             WRITE(*, *) 'NetCDF error in writing singular vectors, no.', k,' rank',i
     END DO

  END DO writevectors

  ! Close file
  s = 1
  stat(s) = NF_CLOSE(ncid_out)

! ********************
! *** Finishing up ***
! ********************

  DEALLOCATE(states, states8, meanstate)
  DEALLOCATE(svals, svdU)

  WRITE (*,'(/1x,a/)') '------- END -------------'

END PROGRAM generate_covar



















